version: '3.8'

services:
  odoo_db:
    image: postgres:16-alpine
    container_name: odoo_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  odoo:
    image: odoo:17
    container_name: odoo_app
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=odoo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./inventory_external_viewer:/mnt/extra-addons/inventory_external_viewer
      - odoo_data:/var/lib/odoo
    command: >
      odoo --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons 
      --dev=reload,qweb,werkzeug,xml

volumes:
  odoo_db_data:
  odoo_data:

